"""Create initial tables

Revision ID: 78e35ce9e33a
Revises: 
Create Date: 2026-01-14 22:23:23.903259

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '78e35ce9e33a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alert_history_alert_type'), 'alert_history', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_history_id'), 'alert_history', ['id'], unique=False)
    op.drop_index(op.f('idx_session_date'), table_name='driving_sessions')
    op.create_index(op.f('ix_driving_sessions_id'), 'driving_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_driving_sessions_start_time'), 'driving_sessions', ['start_time'], unique=False)
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.drop_index(op.f('username'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_index(op.f('ix_driving_sessions_start_time'), table_name='driving_sessions')
    op.drop_index(op.f('ix_driving_sessions_id'), table_name='driving_sessions')
    op.create_index(op.f('idx_session_date'), 'driving_sessions', ['start_time'], unique=False)
    op.drop_index(op.f('ix_alert_history_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alert_type'), table_name='alert_history')
    # ### end Alembic commands ###
